Repository NebulousLabs/Sia, pull requests merged in 2018-04, with the labels that each got.

#2926 only add addrs relevant to the wallet
  modules/wallet/database.go
  modules/wallet/update.go
Labels: in progress

#2932 Fix NDF in siatest/renter package
  siatest/testgroup.go
Labels: in progress

#2933 log contract ID on contract formation
  modules/renter/contractor/contracts.go
Labels: in progress

#2937 update /consensus/blocks endpoint docs
  doc/API.md
  doc/api/Consensus.md
Labels: in progress

#2939 Improve contractor fee reporting
  cmd/siac/rentercmd.go
  doc/API.md
  doc/api/Renter.md
  modules/renter.go
  modules/renter/contractor/contractor.go
  modules/renter/contractor/contractor_test.go
  node/api/renter_test.go
  siatest/testgroup.go
Labels: in progress

#2949 Update siac to use node.api.Client package and add flag to change UserAgent
  cmd/siac/consensuscmd.go
  cmd/siac/daemoncmd.go
  cmd/siac/export.go
  cmd/siac/gatewaycmd.go
  cmd/siac/hostcmd.go
  cmd/siac/hostdbcmd.go
  cmd/siac/main.go
  cmd/siac/minercmd.go
  cmd/siac/rentercmd.go
  cmd/siac/walletcmd.go
  node/api/client/daemon.go
  node/api/client/gateway.go
  node/api/client/host.go
  node/api/client/hostdb.go
  node/api/client/miner.go
  node/api/client/renter.go
  node/api/client/transactionpool.go
  node/api/client/wallet.go
  node/api/daemon.go
  node/api/wallet.go
  siatest/testgroup.go
Labels: in progress

#2956 Updates to Guide to Contributing to Sia
  doc/Guide to Contributing to Sia.md
Labels: Documentation, in progress

#2960 Improve tpool panic output
  modules/transactionpool/update.go
Labels: in progress

#2961 Add new contributors, fix goreport misspell
  doc/Contributors.md
  siatest/renter.go
Labels: Documentation

#2966 Add siac command to get data from /host/contracts endpoint (squashed and rebased)
  cmd/siac/hostcmd.go
  cmd/siac/main.go
  node/api/client/host.go
Labels: in progress
