Repository NebulousLabs/Sia, pull requests merged in 2018-06, with the labels that each got.

#3082 Update `siac renter` to show total data and number of contracts
  cmd/siac/rentercmd.go
Labels: v1.3.4

#3057 Replace TestRedundancyReporting with siatest
  node/api/renterhost_test.go
  siatest/gateway.go
  siatest/renter/renter_test.go
  siatest/testgroup.go
  siatest/testnode.go
Labels: v1.3.4

#3074 Add hostdb endpoint to indicate intial scan status and queued scans
  doc/API.md
  doc/api/HostDB.md
  modules/renter.go
  modules/renter/hostdb/hostdb.go
  modules/renter/hostdb/scan.go
  modules/renter/renter.go
  modules/renter/renter_test.go
  node/api/client/hostdb.go
  node/api/hostdb.go
  node/api/routes.go
  node/node.go
  siatest/renter/dependencies.go
  siatest/renter/hostdb_test.go
  siatest/testgroup.go
Labels: v1.3.4

#3098 Update stream cache to prevent duplicate chunks being added
  modules/renter/contractor/contractor_test.go
  modules/renter/contractor/update_test.go
  modules/renter/streamcache.go
  modules/renter/streamcache_test.go
  siatest/renter/renter_test.go
Labels: Bug, v1.3.3

#3097 Fix -1 Integer Parsing
  node/api/wallet.go
  node/api/wallet_test.go
Labels: Bug, v1.3.3

#3066 Switch from FileContractIDs to HostPubKeys for contractor interface
  modules/host/host.go
  modules/renter.go
  modules/renter/contractor/contractor.go
  modules/renter/contractor/contractor_test.go
  modules/renter/contractor/contracts.go
  modules/renter/contractor/downloader.go
  modules/renter/contractor/editor.go
  modules/renter/contractor/host_integration_test.go
  modules/renter/contractor/persist.go
  modules/renter/contractor/persist_test.go
  modules/renter/contractor/update_test.go
  modules/renter/contractor/uptime.go
  modules/renter/download.go
  modules/renter/downloadchunk.go
  modules/renter/files.go
  modules/renter/proto/contract.go
  modules/renter/proto/contract_test.go
  modules/renter/proto/contractset.go
  modules/renter/proto/contractset_test.go
  modules/renter/renter.go
  modules/renter/uploadheap.go
  modules/renter/workerdownload.go
  modules/renter/workerupload.go
  node/api/renter.go
Labels: v1.3.4

#3083 Detect when local file is lost before 1x redundancy
  cmd/siac/rentercmd.go
  modules/renter/download.go
  modules/renter/downloadchunk.go
  modules/renter/downloaddestination.go
  modules/renter/uploadheap.go
  node/api/renter.go
Labels: v1.3.4

#3087 Fix renter spending reporting and current period
  cmd/siac/export.go
  cmd/siac/main.go
  cmd/siac/rentercmd.go
  modules/renter.go
  modules/renter/contractor/contractor.go
  modules/renter/contractor/contractor_test.go
  modules/renter/contractor/contracts.go
  modules/renter/contractor/update_test.go
  modules/renter/renter.go
  node/api/renter.go
  siatest/renter.go
  siatest/renter/renter_test.go
Labels: v1.3.4

#3073 Fix bug where API password was being printed
  cmd/siac/main.go
Labels: Bug, v1.3.4

#3110 Add async flag to siac renter download
  cmd/siac/main.go
  cmd/siac/rentercmd.go
Labels: v1.3.4
